import markdown as md
from weasyprint import HTML, CSS

_CSS = CSS(string="""
@page {
    margin: 2cm 2.5cm;
    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #9ca3af;
    }
}

body {
    font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #111827;
}

h1 { font-size: 22pt; color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 6pt; margin-top: 0; }
h2 { font-size: 16pt; color: #1e40af; margin-top: 20pt; }
h3 { font-size: 13pt; color: #374151; margin-top: 14pt; }

p  { margin: 6pt 0; }
ul, ol { margin: 6pt 0 6pt 18pt; }
li { margin-bottom: 3pt; }

code {
    font-family: "Courier New", Courier, monospace;
    font-size: 9.5pt;
    background: #f3f4f6;
    padding: 1pt 4pt;
    border-radius: 3pt;
}

pre {
    background: #f3f4f6;
    border-left: 4pt solid #6366f1;
    padding: 10pt 14pt;
    border-radius: 4pt;
    overflow-x: auto;
    font-size: 9pt;
    line-height: 1.5;
}

pre code {
    background: none;
    padding: 0;
}

blockquote {
    border-left: 4pt solid #d1d5db;
    margin: 0;
    padding: 4pt 14pt;
    color: #6b7280;
}

table {
    border-collapse: collapse;
    width: 100%;
    margin: 10pt 0;
}

th {
    background: #1e40af;
    color: white;
    padding: 6pt 10pt;
    text-align: left;
    font-size: 10pt;
}

td {
    padding: 5pt 10pt;
    border-bottom: 1pt solid #e5e7eb;
    font-size: 10pt;
}

tr:nth-child(even) td { background: #f9fafb; }

strong { color: #111827; }
a { color: #2563eb; }

.report-header {
    background: linear-gradient(135deg, #1e3a8a, #7c3aed);
    color: white;
    padding: 20pt 24pt;
    border-radius: 6pt;
    margin-bottom: 20pt;
}

.report-header h1 {
    color: white;
    border-bottom: none;
    margin: 0;
    font-size: 20pt;
}

.report-header p {
    color: rgba(255,255,255,0.8);
    margin: 4pt 0 0 0;
    font-size: 10pt;
}
""")


def render_pdf(markdown_text: str, title: str = "Code Quality Report") -> bytes:
    html_body = md.markdown(
        markdown_text,
        extensions=["fenced_code", "tables", "nl2br", "sane_lists"],
    )
    html = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>{title}</title></head>
<body>
  <div class="report-header">
    <h1>{title}</h1>
    <p>Generated by Code Quality Advisor</p>
  </div>
  {html_body}
</body>
</html>"""
    return HTML(string=html).write_pdf(stylesheets=[_CSS])
